//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalRDenemeMvc.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class danisanTahlilDosyas
    {
        public int DanisanTahlilDosyaID { get; set; }
        public string DanisanDosyaTuru { get; set; }
        public System.DateTime YuklenmeTarihi { get; set; }
        public string DosyaAdi { get; set; }
        public int DanisanID { get; set; }
    
        public virtual Danisans Danisans { get; set; }
    }
}
