//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalRDenemeMvc.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DiyetisyenDBEntities : DbContext
    {
        public DiyetisyenDBEntities()
            : base("name=DiyetisyenDBEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Besinlers> Besinlers { get; set; }
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<Danisans> Danisans { get; set; }
        public virtual DbSet<danisanTahlilDosyas> danisanTahlilDosyas { get; set; }
        public virtual DbSet<Denemes> Denemes { get; set; }
        public virtual DbSet<DiyetSablons> DiyetSablons { get; set; }
        public virtual DbSet<Gorusmelers> Gorusmelers { get; set; }
        public virtual DbSet<OgunIcerikleris> OgunIcerikleris { get; set; }
        public virtual DbSet<Ogunlers> Ogunlers { get; set; }
    }
}
