//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalRDenemeMvc.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gorusmelers
    {
        public int GorusmeID { get; set; }
        public string Alerji { get; set; }
        public string GenetikHastalik { get; set; }
        public string AiledeHastalik { get; set; }
        public string Aktivite { get; set; }
        public string Aciklama { get; set; }
        public string Kullanilanilac { get; set; }
        public System.DateTime GorusmeTarihi { get; set; }
        public int DanisanID { get; set; }
        public float GuncelKilo { get; set; }
        public int BacakCM { get; set; }
        public int BasenCM { get; set; }
        public int BelCM { get; set; }
        public int GogusCM { get; set; }
        public int KalcaCM { get; set; }
        public int KolCM { get; set; }
        public int YagOranı { get; set; }
    
        public virtual Danisans Danisans { get; set; }
    }
}
