//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalRDenemeMvc.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ogunlers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ogunlers()
        {
            this.OgunIcerikleris = new HashSet<OgunIcerikleris>();
        }
    
        public int OgunID { get; set; }
        public string OgunAdi { get; set; }
        public Nullable<int> DiyetSablonID { get; set; }
        public Nullable<int> BesinlerBesinID { get; set; }
    
        public virtual Besinlers Besinlers { get; set; }
        public virtual DiyetSablons DiyetSablons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OgunIcerikleris> OgunIcerikleris { get; set; }
    }
}
